// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClf4ys7GZ_JW4qewiUCupEpSl8nicDkgQ',
    appId: '1:70563809020:web:7c0ed4b6c4c16f84233979',
    messagingSenderId: '70563809020',
    projectId: 'taskmanagemanetapp',
    authDomain: 'taskmanagemanetapp.firebaseapp.com',
    storageBucket: 'taskmanagemanetapp.appspot.com',
    measurementId: 'G-RZX7D4PB2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFRBfBr3VjtRI3ll-0GAwIGZM6_89vJhA',
    appId: '1:70563809020:android:ff6218c5df63616f233979',
    messagingSenderId: '70563809020',
    projectId: 'taskmanagemanetapp',
    storageBucket: 'taskmanagemanetapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeoAWfkAsCD0vSYgHU53ptQJlaUjlaHK8',
    appId: '1:70563809020:ios:6a24469bd9e8242b233979',
    messagingSenderId: '70563809020',
    projectId: 'taskmanagemanetapp',
    storageBucket: 'taskmanagemanetapp.appspot.com',
    iosBundleId: 'com.example.taskManagemetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeoAWfkAsCD0vSYgHU53ptQJlaUjlaHK8',
    appId: '1:70563809020:ios:6a24469bd9e8242b233979',
    messagingSenderId: '70563809020',
    projectId: 'taskmanagemanetapp',
    storageBucket: 'taskmanagemanetapp.appspot.com',
    iosBundleId: 'com.example.taskManagemetApp',
  );
}
